services:
  accounts:
    image: "pgcalixto/accounts:4.0.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - calixtobank_network

  loans:
    image: "pgcalixto/loans:4.0.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - calixtobank_network

  cards:
    image: "pgcalixto/cards:4.0.0"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - calixtobank_network

networks:
  calixtobank_network:
    driver: "bridge"
